### ISSUE TITLE
Title ustawiony w configu nie wyświetla się

### ISSUE THREAD

**Issue by querko216** [P3ridot/YetAnotherMessagesLibrary#6]
Witam,
Nie wiem czy to problem z tą biblioteką, ale jak w configu daje title np.
collectRewardInfo:
  title:
    title: CODZIENNA NAGRODA
    subtitle: /odbierz
    fade-in: 5
    stay: 60
    fade-out: 5

Niestety title nie pojawia się, natomiast wiadomość na czacie już tak. Korzystam z wersji 5.3.0 oraz kyori adventure w wersji 4.12.0
Mój kod: https://github.com/querko216/AfteroweDaily
Dla przykładu pod komendą /daily set powinno pojawić się title 
[DailyCommand.java](https://github.com/querko216/AfteroweDaily/blob/6238ecbd306edea028f504e9769ba8617dcec3d4/src/main/java/pl/aftermc/daily/command/DailyCommand.java#L32)
Reszta kodu:
[AfterMessageDispatcher.java](https://github.com/querko216/AfteroweDaily/blob/master/src/main/java/pl/aftermc/daily/util/AfterMessageDispatcher.java)
[MessageService.java](https://github.com/querko216/AfteroweDaily/blob/master/src/main/java/pl/aftermc/daily/util/MessageService.java)

**Comment by P3ridot** [comment]
A jeśli ustawisz inny typ wiadomości (np. normalnie na chat) to się wysyła? Czy też nie

**Comment by querko216** [comment]
Na czacie wysyła się. Tylko z title, bossbar i actionbar jest problem

**Comment by P3ridot** [comment]
A gdybyś zrelokował adventure w swojej libce? Chyba że testujesz na czystym spigocie a nie na paperze. Jesli na paperze to domyslam sie że bez tej relokacji może się coś gryźć...

**Comment by querko216** [comment]
O dziwo działa, jejku ja z tym wczoraj 5 godzin walczyłem. Mam pytanie da się jakoś pominąć klasę [AfterMessageDispatcher.java](https://github.com/querko216/AfteroweDaily/blob/master/src/main/java/pl/aftermc/daily/util/AfterMessageDispatcher.java)? Bo w niej i tak nic nie ma a nie wiem jak to mogę inaczej zrobić

**Comment by P3ridot** [comment]
w MessageService spróboj wymienić `AfterMessageDispatcher` na po prostu `BukkitMessageDispatcher`, ewentualnie jakby nie działało coś to spróboj `BukkitMessageDispatcher<BukkitMessageDispatcher>` jako typ generyczny... Troche tricky ale powinno zadziałać

**Comment by P3ridot** [comment]
I skoro problem został rozwiązany to zamykam

**Comment by P3ridot** [comment]
> w MessageService spróboj wymienić `AfterMessageDispatcher` na po prostu `BukkitMessageDispatcher`, ewentualnie jakby nie działało coś to spróboj `BukkitMessageDispatcher<BukkitMessageDispatcher>` jako typ generyczny... Troche tricky ale powinno zadziałać

https://github.com/P3ridot/YetAnotherMessagesLibrary/issues/5#issuecomment-1469103938 -> Zaktualizuj do `6.0.0` i stwórz sobie po prostu `BukkitMessageService` i tyle powinno wystarczyć

**Comment by querko216** [comment]
Kurcze coś mi nie wychodzi, mógłbyś wysłać całą klasę MessageService jak powinna wyglądać?

**Comment by P3ridot** [comment]
Zrobiłem [example](https://github.com/P3ridot/YetAnotherMessagesLibrary/blob/master/example/src/main/java/dev/peri/yetanothermessageslibrary/example/ExamplePlugin.java). W twoim przypadku zrób aby twój MessageService po prostu rozszerzał `BukkitMessageService` i zaimplementuj sobie nowy konstruktor. Powinno zadziałać
