### ISSUE TITLE
MessageDispatcher#receivers not working properly

### ISSUE THREAD

**Issue by querko216** [P3ridot/YetAnotherMessagesLibrary#8]
Wersja libki: 6.2.0
Kod:
        this.getMessageService().getMessage(config -> config.chatOnBroadcast)
                .with(Replacement.of("{admin}", sender.getName()))
                .broadcastPlayers().send();
Tak samo .receivers(Bukkit.getOnlinePlayers()).send(); nie wysyła wiadomości na czacie, natomiast wiadomość pokazuje się tylko w konsoli jeśli użyje .broadcast().send();

W fg jest to samo, więc to raczej problem z libką

**Comment by P3ridot** [comment]
Naprawion w 9134d176bd97478a2640e9efd98240c4635a985e - podbij wersje do 6.2.1
